'use strict';
const $=id=>document.getElementById(id), cfg=window.TRACKER_CONFIG||{}, base=(cfg.supabaseUrl||'').replace(/\/$/,''), key=cfg.supabasePublishableKey||'';
let session=null,staff=null,tab='shipped',page=0,total=0,files=[],draft=null,busy=false,serial=0,refreshPromise=null;
const PAGE=30, statuses={packed:'Packed',waybill:'Waybill attached',shipped:'Shipped',pending:'Pending',followup:'Kulang shipped',resolved:'Resolved'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
const when=d=>new Date(d).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});
const configured=()=>/^https:\/\//.test(base)&&!base.includes('YOUR_PROJECT')&&key&&!key.includes('YOUR_');
function storeSession(s){session=s?{...s,expires_at:s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600)}:null;if(session)sessionStorage.setItem('2fly-dispatch-session',JSON.stringify(session));else sessionStorage.removeItem('2fly-dispatch-session');}
async function raw(path,options={}){const response=await fetch(base+path,options);const text=await response.text();let data;try{data=text?JSON.parse(text):null;}catch{throw Error('Unexpected server response. Check your Supabase URL.');}if(!response.ok){const error=Error(data?.msg||data?.message||data?.error_description||data?.error||'Request failed');error.status=response.status;throw error;}return {data,response};}
async function refreshSession(){if(!session)throw Error('Please sign in.');if(session.expires_at*1000>Date.now()+60000)return;if(!refreshPromise)refreshPromise=raw('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}).then(r=>storeSession(r.data)).catch(e=>{if(e.status===400||e.status===401){storeSession(null);showLogin('Session expired. Sign in again.');}throw e;}).finally(()=>{refreshPromise=null;});await refreshPromise;}
async function api(path,options={}){await refreshSession();return raw(path,{...options,headers:{apikey:key,Authorization:'Bearer '+session.access_token,...options.headers}});}
function rpc(action,id,data){return api('/rest/v1/rpc/save_dispatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_action:action,p_id:id,p_data:data})});}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,4500);}
function showLogin(message=''){serial++;$('workspace').hidden=true;$('account').hidden=true;$('login').hidden=false;$('loginError').textContent=message;}
async function start(){const {data}=await api('/rest/v1/dispatch_staff?select=name,active&user_id=eq.'+encodeURIComponent(session.user.id));if(!data[0]?.active)throw Error('Your account is not approved. Ask your administrator to add you to dispatch_staff.');staff=data[0];$('staff').textContent=staff.name;$('login').hidden=true;$('workspace').hidden=false;$('account').hidden=false;setTab(tab);}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!configured()){showLogin('Setup required: add your Supabase URL and public key to config.js. See START-HERE.md in the ZIP.');return;}const button=e.target.querySelector('button');button.disabled=true;$('loginError').textContent='';try{const values=Object.fromEntries(new FormData(e.target));const {data}=await raw('/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(values)});storeSession(data);e.target.reset();await start();}catch(error){showLogin(error.message);}finally{button.disabled=false;}};
$('logout').onclick=async()=>{try{await api('/auth/v1/logout',{method:'POST'});}catch{}storeSession(null);files.forEach(f=>URL.revokeObjectURL(f.url));files=[];document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('detailBody').replaceChildren();$('records').replaceChildren();showLogin();};
async function load(){const request=++serial;$('loadError').textContent='';$('records').innerHTML='<div class="empty">Loading records…</div>';try{const params=new URLSearchParams({select:'*',kind:'eq.'+tab,order:'created_at.desc',limit:String(PAGE),offset:String(page*PAGE)});const q=$('search').value.trim();if(q){const literal=q.replace(/[%_*]/g,'').replace(/\\/g,'\\\\').replace(/"/g,'\\"');params.set('or',`(customer.ilike."*${literal}*",reference.ilike."*${literal}*",tracking.ilike."*${literal}*")`);}if($('status').value!=='all')params.set('status','eq.'+$('status').value);const {data,response}=await api('/rest/v1/dispatch_records?'+params,{headers:{Prefer:'count=exact'}});if(request!==serial)return;total=Number((response.headers.get('content-range')||'0/0').split('/')[1])||0;$('records').innerHTML=data.length?data.map(r=>`<article class="entry"><div><strong>${esc(r.customer)}</strong><small>${esc(r.reference)}</small></div><div class="wrap">${esc(tab==='missing'?r.missing:r.courier)}<small>${esc(tab==='missing'?'':r.tracking)}</small></div><div><span class="badge ${esc(r.status)}">${esc(statuses[r.status])}</span></div><div><small>${esc(r.staff)}</small><small>${esc(when(r.created_at))} · ${r.photos.length} photos</small></div><button class="secondary" data-detail="${r.id}">View →</button></article>`).join(''):`<div class="empty"><b>${q?'No matching records':tab==='shipped'?'Your shipment log starts here':'No missing-item records'}</b>${q?'Try a different customer or reference.':'Use the button above to add your first record.'}</div>`;$('count').textContent=total?`${page*PAGE+1}–${Math.min((page+1)*PAGE,total)} of ${total} records`:'0 records';$('prev').disabled=page===0;$('next').disabled=(page+1)*PAGE>=total;}catch(e){if(request===serial){$('records').replaceChildren();$('loadError').textContent=e.message;}}}
function setTab(value){tab=value;page=0;$('status').hidden=false;$('status').innerHTML='<option value="all">All statuses</option>'+(value==='shipped'?['packed','waybill','shipped']:['pending','followup','resolved']).map(s=>`<option value="${s}">${statuses[s]}</option>`).join('');$('status').value='all';$('add').textContent=value==='shipped'?'＋ Add parcel':'＋ Report missing items';for(const k of ['shipped','missing']){$(k+'Tab').classList.toggle('active',k===value);$(k+'Tab').setAttribute('aria-pressed',String(k===value));}load();}
$('shippedTab').onclick=()=>setTab('shipped');$('missingTab').onclick=()=>setTab('missing');$('refresh').onclick=load;$('status').onchange=()=>{page=0;load();};let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=0;load();},300);};$('prev').onclick=()=>{if(page>0){page--;load();}};$('next').onclick=()=>{page++;load();};$('records').onclick=e=>{const b=e.target.closest('[data-detail]');if(b)detail(b.dataset.detail);};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!busy)$(b.dataset.close).close();});$('editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
function openEditor(record=null,action='followup'){draft={id:record?.id||crypto.randomUUID(),operation:crypto.randomUUID(),action:record?action:'create',kind:record?record.kind:tab};files.forEach(f=>URL.revokeObjectURL(f.url));files=[];renderFiles();$('recordForm').reset();$('formError').textContent='';$('formTitle').textContent=record?(action==='update'?'Add photos / tracking':'Ship missing items'):tab==='shipped'?'Add parcel':'Report missing items';$('updateStage').hidden=!(record&&action==='update');$('formHint').textContent=record?(action==='update'?'Add proof to this same record. Original photos will stay here.':'Record after courier handover. Tracking can be added later.'):'Save shop parcel photos now; shipment staff adds waybill proof later.';$('identity').hidden=!!record;const shipping=!!record||tab==='shipped';$('shippingFields').hidden=!shipping;$('missingFields').hidden=shipping;for(const name of ['customer','reference'])$('recordForm').elements[name].required=!record;$('recordForm').elements.missing.required=!shipping;$('recordForm').elements.tracking.required=false;const isFollowup=!!record&&action==='followup';$('dateField').hidden=!isFollowup;$('recordForm').elements.ship_date.required=isFollowup;$('photoLabel').textContent=record&&action==='update'?'Additional proof':'Photo proof · required';if(record){$('recordForm').elements.tracking.value=record.tracking||'';$('recordForm').elements.courier.value=record.courier||'J&T Express';}$('recordForm').elements.ship_date.value=today();$('recordForm').elements.ship_date.max=today();$('details').close();$('editor').showModal();}
$('add').onclick=()=>openEditor();
function renderFiles(){$('files').innerHTML=files.map((f,i)=>`<div class="file"><img src="${f.url}" alt="Selected photo preview"><span>${esc(f.file.name)}</span><button type="button" aria-label="Remove photo ${i+1}" data-remove="${i}">×</button></div>`).join('');}
function addPhotos(input){const incoming=[...input.files];input.value='';if(files.length+incoming.length>4){$('formError').textContent='Up to 4 photos per record.';return;}if(incoming.some(f=>f.size>8*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){$('formError').textContent='Use JPG, PNG or WebP photos, 8 MB or less each.';return;}$('formError').textContent='';files.push(...incoming.map(file=>({file,url:URL.createObjectURL(file),path:null})));renderFiles();}
$('camera').onchange=e=>addPhotos(e.target);$('gallery').onchange=e=>addPhotos(e.target);$('files').onclick=e=>{const b=e.target.closest('[data-remove]');if(b&&!busy){URL.revokeObjectURL(files[+b.dataset.remove].url);files.splice(+b.dataset.remove,1);renderFiles();}};
$('recordForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const data=Object.fromEntries(new FormData(e.target));const needsPhotos=draft.action!=='update'||data.stage==='waybill';if(needsPhotos&&!files.length){$('formError').textContent='Add at least one photo.';return;}if(!needsPhotos&&!files.length&&!data.tracking.trim()&&!data.notes.trim()){$('formError').textContent='Add a photo, tracking number, or note.';return;}busy=true;data.kind=draft.kind;data.operation_id=draft.operation;$('save').textContent='Uploading…';$('formError').textContent='';const controls=[...e.target.querySelectorAll('input,select,textarea,button')];controls.forEach(c=>c.disabled=true);try{for(const f of files){if(f.path)continue;const path=session.user.id+'/'+crypto.randomUUID()+({ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp'}[f.file.type]);await api('/storage/v1/object/dispatch-proof/'+path,{method:'POST',headers:{'Content-Type':f.file.type,'x-upsert':'false'},body:f.file});f.path=path;}data.photos=files.map(f=>({path:f.path}));$('save').textContent='Saving…';await rpc(draft.action,draft.id,data);$('editor').close();files.forEach(f=>URL.revokeObjectURL(f.url));files=[];toast('Record saved');load();}catch(error){$('formError').textContent=error.message+' Your form has been kept. If a retry says the record changed, close this form and refresh to check whether it saved.';}finally{busy=false;controls.forEach(c=>c.disabled=false);$('save').textContent='Save record';}};
async function signed(path){const {data}=await api('/storage/v1/object/sign/dispatch-proof/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:300})});return base+'/storage/v1'+data.signedURL;}
async function detail(id){$('detailBody').textContent='Loading…';$('details').showModal();try{const {data}=await api('/rest/v1/dispatch_records?select=*&id=eq.'+encodeURIComponent(id));const r=data[0];if(!r)throw Error('Record not found.');$('detailBody').innerHTML=`<h3>${esc(r.customer)}</h3><p>${esc(r.reference)} · <span class="badge ${esc(r.status)}">${esc(statuses[r.status])}</span></p>${r.missing?`<div class="missingbox"><strong>Missing items</strong><br>${esc(r.missing)}</div>`:''}${r.tracking?`<p class="wrap">${esc(r.courier)} · ${esc(r.ship_date)}<br><strong>${esc(r.tracking)}</strong></p>`:''}<p class="wrap">${esc(r.notes)}</p>${!r.tracking?'<p>Tracking number: not added yet</p>':''}<h3>Photo proof</h3><p class="hint">Tap a photo to open it. Photo links expire after 5 minutes; reopen this record to refresh.</p><div class="photos" id="proofs"></div><h3>Record history</h3><div class="history">${r.history.map(h=>`<p class="wrap">${esc(h.action)}${h.tracking?' · '+esc(h.tracking):''}<small>${esc(h.staff)} · ${esc(when(h.at))}</small>${h.notes?'<small>'+esc(h.notes)+'</small>':''}</p>`).join('')}</div><h3>Other records for this order</h3><div id="related"></div><button id="addProof" class="primary">Add photos / tracking</button>${['packed','waybill'].includes(r.status)?'<button id="dispatch" class="secondary">Mark handed to courier</button>':''}${r.status==='pending'?'<button id="followup" class="primary">Record follow-up shipment</button>':r.status==='followup'?'<p>Resolve once the missing-item issue is fully settled.</p><button id="resolve" class="primary">Mark resolved</button>':''}`;
$('addProof').onclick=()=>openEditor(r,'update');if($('dispatch'))$('dispatch').onclick=async e=>{if(!confirm('Confirm this parcel has actually been handed to the courier?'))return;e.target.disabled=true;try{await rpc('dispatch',r.id,{ship_date:today(),operation_id:crypto.randomUUID()});toast('Marked shipped');$('details').close();load();}catch(error){toast(error.message);e.target.disabled=false;}};if($('followup'))$('followup').onclick=()=>openEditor(r);if($('resolve'))$('resolve').onclick=async e=>{e.target.disabled=true;try{await rpc('resolve',r.id,{});toast('Marked resolved');$('details').close();load();}catch(error){toast(error.message);e.target.disabled=false;}};
const target=$('proofs');await Promise.all(r.photos.map(async p=>{const container=document.createElement('div');target.append(container);try{const url=await signed(p.path);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=url;img.alt=p.stage==='followup'?'Follow-up shipment proof':'Original proof';a.append(img);container.append(a);const label=document.createElement('small');label.textContent=({followup:'Follow-up shipment',waybill:'Waybill attached',parcel:'Parcel photo',additional:'Additional proof',original:'Original proof'}[p.stage]||'Proof')+(p.staff?' · '+p.staff:'')+(p.at?' · '+when(p.at):'');container.append(label);}catch{container.textContent='Photo unavailable. Reopen to retry.';}}));
const params=new URLSearchParams({select:'id,kind,status',reference:'eq.'+r.reference,id:'neq.'+r.id,limit:'50'});const relatedTarget=$('related');const related=await api('/rest/v1/dispatch_records?'+params);if(!relatedTarget?.isConnected)return;relatedTarget.replaceChildren();if(!related.data.length)relatedTarget.textContent='No other records.';related.data.forEach(x=>{const button=document.createElement('button');button.className='secondary';button.textContent=(x.kind==='missing'?'Missing items':'Shipment')+' · '+statuses[x.status];button.onclick=()=>detail(x.id);relatedTarget.append(button);});}catch(e){$('detailBody').textContent=e.message;}}
(async()=>{if(!configured()){showLogin('Setup required: edit config.js using START-HERE.md before signing in.');return;}try{session=JSON.parse(sessionStorage.getItem('2fly-dispatch-session')||'null');if(session)await start();}catch(e){showLogin(e.message);}})();
